/* Processed by ecpg (4.8.0) */
/* These include files are added by the preprocessor */
#include <ecpglib.h>
#include <ecpgerrno.h>
#include <sqlca.h>
/* End of automatic include section */

#line 1 "program.pgc"
//--first--
/*
 * File - "program.pgc"
 * Desc - This is the program generated by our engine.
 * Team - SDE(Stevens Dota Elites/Software Development Engineers).
 * Memb - Gong Cheng 	10390440
 *	  Lingzhi Yuan	10391683
 *	  Yanjun Wu	10392467
 *	  Zhe Xu	10393213
 *
 * Steps to run this program : (Make sure you have installed postgresql and ecpg)
 *  1. Log in to PostgreSQL server.
 *  2. In the DATABASE CONNECTION, modify [dbname], [host], [port], [username], [password] to
 *     yours ([dbname] is the same as your [username] by default).
 *  3. Preprocessor - $ ecpg -I /usr/include/postgresql program.pgc
 *  4. Compile      - $ gcc -c -I /usr/include/postgresql/ program.c
 *  5. Link         - $ gcc -L /usr/include/postgresql/ program.o -lecpg -o program
 *  6. Execute      - $ ./program
 */

//--------------------------------------
//including libraries (all standard libraries)
//--------------------------------------
#include <stdio.h>
#include <stdlib.h>
#include <string.h> // used for string comparison
//--------------------------------------

//----------------------------------------------------------------------
// Host variables define
//----------------------------------------------------------------------
/* exec sql begin declare section */
 
		
		
		
		
	

#line 38 "program.pgc"
 struct { 
#line 34 "program.pgc"
 char * prod ;
 
#line 35 "program.pgc"
 long mm ;
 
#line 36 "program.pgc"
 long quant ;
 
#line 37 "program.pgc"
 long yy ;
 } sale_rec ;
/* exec sql end declare section */
#line 39 "program.pgc"


#line 1 "/usr/include/postgresql/sqlca.h"
#ifndef POSTGRES_SQLCA_H
#define POSTGRES_SQLCA_H

#ifndef PGDLLIMPORT
#if  defined(WIN32) || defined(__CYGWIN__)
#define PGDLLIMPORT __declspec (dllimport)
#else
#define PGDLLIMPORT
#endif   /* __CYGWIN__ */
#endif   /* PGDLLIMPORT */

#define SQLERRMC_LEN	150

#ifdef __cplusplus
extern		"C"
{
#endif

struct sqlca_t
{
	char		sqlcaid[8];
	long		sqlabc;
	long		sqlcode;
	struct
	{
		int			sqlerrml;
		char		sqlerrmc[SQLERRMC_LEN];
	}			sqlerrm;
	char		sqlerrp[8];
	long		sqlerrd[6];
	/* Element 0: empty						*/
	/* 1: OID of processed tuple if applicable			*/
	/* 2: number of rows processed				*/
	/* after an INSERT, UPDATE or				*/
	/* DELETE statement					*/
	/* 3: empty						*/
	/* 4: empty						*/
	/* 5: empty						*/
	char		sqlwarn[8];
	/* Element 0: set to 'W' if at least one other is 'W'	*/
	/* 1: if 'W' at least one character string		*/
	/* value was truncated when it was			*/
	/* stored into a host variable.             */

	/*
	 * 2: if 'W' a (hopefully) non-fatal notice occurred
	 */	/* 3: empty */
	/* 4: empty						*/
	/* 5: empty						*/
	/* 6: empty						*/
	/* 7: empty						*/

	char		sqlstate[5];
};

struct sqlca_t *ECPGget_sqlca(void);

#ifndef POSTGRES_ECPG_INTERNAL
#define sqlca (*ECPGget_sqlca())
#endif

#ifdef __cplusplus
}
#endif

#endif

#line 40 "program.pgc"

//----------------------------------------------------------------------
//--end first--

//----------------------------------------------------------------------
// MF Struct define
//----------------------------------------------------------------------
struct m{
	bool flag;
	char prod[21];
	long mm;
	short count_3_quant;
	long sum_1_quant;
	short count_1_quant;
	long avg_1_quant;
	long sum_2_quant;
	short count_2_quant;
	long avg_2_quant;
} MFS[500];
//----------------------------------------------------------------------

//--second--
//----------------------------------------------------------------------
// FUNCTION PROTOTYPE declaration
//----------------------------------------------------------------------
void	initialMFS();
unsigned int	hashFunc(char*);
int compare(const void *p1, const void *p2);
//----------------------------------------------------------------------

int main(int argc, char* argv[])
//----------------------------------------------------------------------
{
   int i;
   initialMFS();
   //----------------------------------------------------------------------
   // DATABASE CONNECTION
   //----------------------------------------------------------------------
   { ECPGconnect(__LINE__, 0, "cs562@localhost:5432" , "postgres" , "cs562" , NULL, 0); }
#line 78 "program.pgc"

   /* exec sql whenever sqlerror  sqlprint ; */
#line 79 "program.pgc"

   //----------------------------------------------------------------------
   // READ RECORDS
   //----------------------------------------------------------------------
   /* declare mycursor cursor for select prod , month , quant , year from sales */
#line 83 "program.pgc"

   { ECPGdo(__LINE__, 0, 1, NULL, 0, ECPGst_normal, "set transaction read only", ECPGt_EOIT, ECPGt_EORT);
#line 84 "program.pgc"

if (sqlca.sqlcode < 0) sqlprint();}
#line 84 "program.pgc"

//--end second--

   // group by grouping attributes,  assigned: Zhe Xu
   // Open cursor
   { ECPGdo(__LINE__, 0, 1, NULL, 0, ECPGst_normal, "declare mycursor cursor for select prod , month , quant , year from sales", ECPGt_EOIT, ECPGt_EORT);
#line 89 "program.pgc"

if (sqlca.sqlcode < 0) sqlprint();}
#line 89 "program.pgc"

   // Fetch Data
   { ECPGdo(__LINE__, 0, 1, NULL, 0, ECPGst_normal, "fetch from mycursor", ECPGt_EOIT, 
	ECPGt_char,&(sale_rec.prod),(long)0,(long)1,(1)*sizeof(char), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, 
	ECPGt_long,&(sale_rec.mm),(long)1,(long)1,sizeof(long), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, 
	ECPGt_long,&(sale_rec.quant),(long)1,(long)1,sizeof(long), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, 
	ECPGt_long,&(sale_rec.yy),(long)1,(long)1,sizeof(long), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, ECPGt_EORT);
#line 91 "program.pgc"

if (sqlca.sqlcode < 0) sqlprint();}
#line 91 "program.pgc"
 //fetch the first row
   while (sqlca.sqlcode == 0) {
    if(sale_rec.yy==1997 ) // condition for where clause
    {
	unsigned int hash = hashFunc(sale_rec.prod); // get the hash key
	while(MFS[hash].flag!=false) // solve the collision by using linear probing
	{
		if(strcmp(sale_rec.prod, MFS[hash].prod) == 0 && sale_rec.mm == MFS[hash].mm) break;
		else hash=(hash + 1) % 500;
	}
	if(MFS[hash].flag==false) // if the grouping attributes not exist, insert into table
	{
		for(i = 0; sale_rec.prod[i]!='\0'; i++)
			MFS[hash].prod[i] = sale_rec.prod[i];
		MFS[hash].prod[i] = '\0';
		MFS[hash].mm = sale_rec.mm;
		MFS[hash].count_3_quant = 0;
		MFS[hash].sum_1_quant = 0;
		MFS[hash].count_1_quant = 0;
		MFS[hash].avg_1_quant = 0;
		MFS[hash].sum_2_quant = 0;
		MFS[hash].count_2_quant = 0;
		MFS[hash].avg_2_quant = 0;
		MFS[hash].flag = 1;
	}
    }
      { ECPGdo(__LINE__, 0, 1, NULL, 0, ECPGst_normal, "fetch from mycursor", ECPGt_EOIT, 
	ECPGt_char,&(sale_rec.prod),(long)0,(long)1,(1)*sizeof(char), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, 
	ECPGt_long,&(sale_rec.mm),(long)1,(long)1,sizeof(long), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, 
	ECPGt_long,&(sale_rec.quant),(long)1,(long)1,sizeof(long), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, 
	ECPGt_long,&(sale_rec.yy),(long)1,(long)1,sizeof(long), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, ECPGt_EORT);
#line 117 "program.pgc"

if (sqlca.sqlcode < 0) sqlprint();}
#line 117 "program.pgc"
 //fetch the rest rows
   }
   // Close cursor
   { ECPGdo(__LINE__, 0, 1, NULL, 0, ECPGst_normal, "close mycursor", ECPGt_EOIT, ECPGt_EORT);
#line 120 "program.pgc"

if (sqlca.sqlcode < 0) sqlprint();}
#line 120 "program.pgc"

   //----------------------------------------------------------------------
   //optimization for independent grouping attributes  assigned: Gong Cheng
   //Scan 1
   // Open cursor
   { ECPGdo(__LINE__, 0, 1, NULL, 0, ECPGst_normal, "declare mycursor cursor for select prod , month , quant , year from sales", ECPGt_EOIT, ECPGt_EORT);
#line 125 "program.pgc"

if (sqlca.sqlcode < 0) sqlprint();}
#line 125 "program.pgc"

   // Fetch Data
   { ECPGdo(__LINE__, 0, 1, NULL, 0, ECPGst_normal, "fetch from mycursor", ECPGt_EOIT, 
	ECPGt_char,&(sale_rec.prod),(long)0,(long)1,(1)*sizeof(char), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, 
	ECPGt_long,&(sale_rec.mm),(long)1,(long)1,sizeof(long), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, 
	ECPGt_long,&(sale_rec.quant),(long)1,(long)1,sizeof(long), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, 
	ECPGt_long,&(sale_rec.yy),(long)1,(long)1,sizeof(long), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, ECPGt_EORT);
#line 127 "program.pgc"

if (sqlca.sqlcode < 0) sqlprint();}
#line 127 "program.pgc"
 //fetch the first row
   while (sqlca.sqlcode == 0) {
    if(sale_rec.yy==1997 ) // condition for where clause
    {
	unsigned int hash = hashFunc(sale_rec.prod); // get the hash key
	unsigned int hashScan;
	hashScan = hash;
	for(i = 0; i < 500; i++) // find all the relative entries
	{
		if(MFS[hashScan].flag == 0) break;
		if(strcmp(sale_rec.prod, MFS[hashScan].prod) == 0 && 
		   sale_rec.mm==MFS[hashScan].mm-1 ) // update the entry if conditions match
		{
			MFS[hashScan].sum_1_quant+= sale_rec.quant;
			MFS[hashScan].count_1_quant++;
			MFS[hashScan].avg_1_quant = MFS[hashScan].sum_1_quant / MFS[hashScan].count_1_quant;
		}
		if(strcmp(sale_rec.prod, MFS[hashScan].prod) == 0 && 
		   sale_rec.mm==MFS[hashScan].mm+1 ) // update the entry if conditions match
		{
			MFS[hashScan].sum_2_quant+= sale_rec.quant;
			MFS[hashScan].count_2_quant++;
			MFS[hashScan].avg_2_quant = MFS[hashScan].sum_2_quant / MFS[hashScan].count_2_quant;
		}
		hashScan=(hashScan + 1) % 500;
	}
    }
     { ECPGdo(__LINE__, 0, 1, NULL, 0, ECPGst_normal, "fetch from mycursor", ECPGt_EOIT, 
	ECPGt_char,&(sale_rec.prod),(long)0,(long)1,(1)*sizeof(char), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, 
	ECPGt_long,&(sale_rec.mm),(long)1,(long)1,sizeof(long), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, 
	ECPGt_long,&(sale_rec.quant),(long)1,(long)1,sizeof(long), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, 
	ECPGt_long,&(sale_rec.yy),(long)1,(long)1,sizeof(long), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, ECPGt_EORT);
#line 154 "program.pgc"

if (sqlca.sqlcode < 0) sqlprint();}
#line 154 "program.pgc"
 //fetch the rest rows
   }
   // Close cursor
   { ECPGdo(__LINE__, 0, 1, NULL, 0, ECPGst_normal, "close mycursor", ECPGt_EOIT, ECPGt_EORT);
#line 157 "program.pgc"

if (sqlca.sqlcode < 0) sqlprint();}
#line 157 "program.pgc"

   //----------------------------------------------------------------------

   //Scan 2
   // Open cursor
   { ECPGdo(__LINE__, 0, 1, NULL, 0, ECPGst_normal, "declare mycursor cursor for select prod , month , quant , year from sales", ECPGt_EOIT, ECPGt_EORT);
#line 162 "program.pgc"

if (sqlca.sqlcode < 0) sqlprint();}
#line 162 "program.pgc"

   // Fetch Data
   { ECPGdo(__LINE__, 0, 1, NULL, 0, ECPGst_normal, "fetch from mycursor", ECPGt_EOIT, 
	ECPGt_char,&(sale_rec.prod),(long)0,(long)1,(1)*sizeof(char), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, 
	ECPGt_long,&(sale_rec.mm),(long)1,(long)1,sizeof(long), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, 
	ECPGt_long,&(sale_rec.quant),(long)1,(long)1,sizeof(long), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, 
	ECPGt_long,&(sale_rec.yy),(long)1,(long)1,sizeof(long), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, ECPGt_EORT);
#line 164 "program.pgc"

if (sqlca.sqlcode < 0) sqlprint();}
#line 164 "program.pgc"
 //fetch the first row
   while (sqlca.sqlcode == 0) {
    if(sale_rec.yy==1997 ) // condition for where clause
    {
	unsigned int hash = hashFunc(sale_rec.prod); // get the hash key
	unsigned int hashScan;
	hashScan = hash;
	while(strcmp(MFS[hashScan].prod, sale_rec.prod) != 0 || 
	      MFS[hashScan].mm != sale_rec.mm) // find the exact entry for the MF variable
	{
		hashScan=(hashScan + 1) % 500;
	}
	if(MFS[hashScan].count_1_quant != 0 && sale_rec.quant>MFS[hashScan].avg_1_quant && MFS[hashScan].count_2_quant != 0 && sale_rec.quant<MFS[hashScan].avg_2_quant ) // update the entry if conditions match
	{
		MFS[hashScan].count_3_quant++;
	}
    }
     { ECPGdo(__LINE__, 0, 1, NULL, 0, ECPGst_normal, "fetch from mycursor", ECPGt_EOIT, 
	ECPGt_char,&(sale_rec.prod),(long)0,(long)1,(1)*sizeof(char), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, 
	ECPGt_long,&(sale_rec.mm),(long)1,(long)1,sizeof(long), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, 
	ECPGt_long,&(sale_rec.quant),(long)1,(long)1,sizeof(long), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, 
	ECPGt_long,&(sale_rec.yy),(long)1,(long)1,sizeof(long), 
	ECPGt_NO_INDICATOR, NULL , 0L, 0L, 0L, ECPGt_EORT);
#line 181 "program.pgc"

if (sqlca.sqlcode < 0) sqlprint();}
#line 181 "program.pgc"
 //fetch the rest rows
   }
   // Close cursor
   { ECPGdo(__LINE__, 0, 1, NULL, 0, ECPGst_normal, "close mycursor", ECPGt_EOIT, ECPGt_EORT);
#line 184 "program.pgc"

if (sqlca.sqlcode < 0) sqlprint();}
#line 184 "program.pgc"

   //----------------------------------------------------------------------

	qsort(MFS, 500, sizeof(MFS[0]),compare); // sort the result for clear comparison
	//----------------------------------------------------------------------
	// PRINT TITLE
	//----------------------------------------------------------------------
	printf(" PROD    | MON | COUNT_3_QUANT \n");
	printf("---------+-----+---------------\n");
	for(i = 0; i < 500; i++)
	{
		if(MFS[i].flag==0) break; // break when flag=false, because MFS are sorted
		if(MFS[i].count_3_quant ) // output the result if conditions match
		{
			printf(" %-7s |", MFS[i].prod);
			printf("  %2ld |", MFS[i].mm);
			printf(" %13d \n", MFS[i].count_3_quant);
		}
	}
//--third--
   return 0;
}

//--------------------------------------
// MFS initialization
//--------------------------------------
void	initialMFS()
{
	int i;
	for(i = 0; i < 500; i++)
	{
		MFS[i].flag=0; // set all flags to false
	}
}

//--end third--
  //assigned: Lingzhi Yuan
//--------------------------------------
// Hash function which generate the hash key for the giving parameters
//--------------------------------------
unsigned int	hashFunc(char* prod)
{
	int i;
	unsigned int hash = 0;
	char temp[50]; // used for converting int to string
	for(i = 0; prod[i]!='\0'; i++) // hash function for strings
	{
		hash = (hash<<4)^(hash>>28)^prod[i];
	}
	return (hash%500);
}
int compare(const void *p1, const void *p2) // compare function for MFS quick sort
{
	const struct m *p = p1;
	const struct m *q = p2;
	if(!p->flag) return 1;
	if(!q->flag) return -1;
	// Compare the columns one by one
	if(strcmp(p->prod, q->prod) != 0) return strcmp(p->prod, q->prod);
	if(p->mm != q->mm) return p->mm>q->mm? 1 : -1;
	if(p->count_3_quant != q->count_3_quant) return p->count_3_quant>q->count_3_quant? 1 : -1;
	return 0; // if all equal, return 0
}

